### PR TITLE
trying to support other universities

### PR DESCRIPTION
**Pull request by TheRogue76**
Hi
Thought it would be nice to add more universities. there is a .env file that we can put the server IPs in(or they can just give the server IP.)
I tried to make it compatible with yours but i ended up changing the input arguments a bit. They just need to give the course's subdirectory as an argument now (instead of http://194.225.24.94/po68hagu1ncb/, they just put in po68hagu1ncb.)
Had fun doing this. cya

### CODE REVIEW

**Comment by TheRogue76** [comment]
The check fails because of the .env file included in the project.

**Comment by ParsaHejabi** [comment]
Hi,
Thanks for contributing and sharing your thoughts. However, I think using a file called `ipAddresses.txt` would be much better than using a `.env` file. This way there is no need to import `load_env`.
One more thing is that this code is already working whether you provide a URL or just an ID or even if you download and provide the zip file yourself, so there is no need to add more code for that.
And I updated the .gitignore file to prevent PyCharm from uploading unnecessary files.
Thanks again for sharing your idea. 🙌🏻

**Comment by TheRogue76** [comment]
Thanks for the feedback
I did indeed switch from .env to ipAdresses.txt. the format for each line is 'server_name':'server_ip'. More servers can now be added and it will automatically add them to the prompt. I also had not noticed your code for detecting URL/Code/zip(my bad) so i removed my extra code and updated the README.md file as well to include those options for downloading.
your changes for .gitignore were also merged into mine.
Happy coding

**Comment by ParsaHejabi** [comment]
Thanks a lot, for the great contribution Parsa jan.
Wish you the best luck.

**Pull request merged**
